### ISSUE TITLE
 RFC 2119 有翻译吗？可以在对应的链接地方插入中文版的链接吧

### ISSUE THREAD

**Issue by Clarence-pan** [PizzaLiu/PHP-FIG#9]

**Comment by PizzaLiu** [comment]
http://www.ruanyifeng.com/blog/2007/03/rfc2119.html

个人觉得没有必要

**Comment by Clarence-pan** [comment]
OK 谢谢~  另外，后面有几篇建议从<https://psr.phphub.org/>上合过来

**Comment by PizzaLiu** [comment]
欢迎 pull request
